name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          DATE_TIME="$(date +'%Y.%m.%d.%H.%M')"
          echo "DATE_TIME=$DATE_TIME" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t goveeproxy:$DATE_TIME -f docker/php/Dockerfile.prod . --platform=linux/amd64

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/cookbook:$DATE_TIME
          docker tag goveeproxy:$DATE_TIME ghcr.io/${{ github.repository_owner }}/goveeproxy:latest
          docker push ghcr.io/${{ github.repository_owner }}/goveeproxy:latest